### ISSUE TITLE
hooks in a mixin

### ISSUE THREAD

**Issue by chikamichi** [apotonick/hooks#2]
Hi, taking my example as code base, I turned the Cat class into a module :

``` ruby
require 'hooks'

# That's the generic cat. It does pretty much nothing.
# It's not really a *cat* by the way, just a Ruby class.
# Don't forget to document this properly, cats are literate coders.
module Cat
  include Hooks

  @likes = 'food'
  define_hook :after_dinner # void default implementation

  def dinner_time!
    puts "It's dinner time!"
    run_hook :after_dinner, @likes
  end
end

# But here's *my* REAL cat. It's dumb and hangry. It's a cat.
# MY CAT.
class MyCat
  include Cat

  def initialize(likes = nil)
    @likes = likes ? likes : 'food'
  end

  after_dinner do |what|
    puts "I had a great time. I'd like some more #{what}!"
  end

  after_dinner :want_some_more

  def want_some_more(what)
    puts "No, really, is there some more #{@likes}?"
  end
end

# dumb cat
Cat.new.dinner_time! # => It's dinner time!

# dumber cat
my_cat = MyCat.new('fish')
my_cat.dinner_time!  # => It's dinner time!
                     # => I had a great time. I'd like some more fish!
                     # => No, really, is there some more fish?
```

Running the script shouts:

    tmp_hooks.rb:27:in `<class:MyCat>': undefined method `after_dinner' for MyCat:Class (NoMethodError)
	from tmp_hooks.rb:20:in `<main>'

**Comment by rjurado01** [comment]
Thanks @dorren.
